title: "Johanna Lucille Roberts"
description: "Education and Career Timeline"
theme: jekyll-theme-minimal # Optional fallback, but we will write custom CSS
url: "https://devintobiascolebrooke.github.io"

# Contact Information
email: "johanna@johannalucilleroberts.com"
linkedin: "https://www.linkedin.com/in/johanna-roberts-7bb92321a/"
embark_url: "https://connect.vestwell.com/gift/oregon-college/1byH4tqvzE2-akObncIe9A"